spring:
    profiles: dev
    application:
      name: Marwan App
    thymeleaf:
      cache: false
      enabled: true
      prefix: classpath:/templates/
      suffix: .html
    datasource:      url: jdbc:mysql://localhost:3306/spring?createDatabaseIfNotExist=true
      username: root
      password: marwan
      initialization-mode: always
    jpa:
      properties:        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          id:
            new_generator_mappings: false
      hibernate:        ddl-auto: none
    mail:      host: smtp.gmail.com
      port: 587
      username: marwanayman1998@gmail.com
      password:  evkqolavxbevygrx
      properties:        mail:
          smtp:
            auth: true
            starttls:
              enable: true
 
---
 spring:
    profiles: test
    h2:
      console:
        enabled: true
    application:
      name: Marwan App
    main:
     allow-bean-definition-overriding: true
    thymeleaf:
      cache: false
      enabled: true
      prefix: classpath:/templates/
      suffix: .html

    datasource:
      continue-on-error: true
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create
    mail:
      host: smtp.gmail.com
      port: 587
      username: marwanayman1998@gmail.com
      password:  evkqolavxbevygrx
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
 